### ISSUE TITLE
'ModelResponseStream' object has no attribute 'usage'

### ISSUE THREAD

**Issue by minglu7** [Canner/WrenAI#1721]
**Describe the bug**
I just upgraded to version 0.23.0. Some questions that worked in version 0.22.4 are now throwing errors.
it should happen in the step of generate_sql_reasoning

**To Reproduce**
1. just ask a question

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/fe4ea8e6-499f-487c-a8e0-b5dcba97beab)

![Image](https://github.com/user-attachments/assets/e3ad4571-a6ab-477e-9a46-77df2c6cfebb)

**Desktop (please complete the following information):**

**Wren AI Information**
- Version: [0.23.0]

**Additional context**

**Relevant log output**

```
********************************************************************************
> generate_sql_reasoning [src.pipelines.generation.followup_sql_generation_reasoning.generate_sql_reasoning()] encountered an error<
> Node inputs:
{'generator': '<function LitellmLLMProvider.get_generator.<locals...',
 'generator_name': 'deepseek/deepseek-chat',
 'prompt': "<Task finished name='Task-1587' coro=<AsyncGraphAd...",
 'query_id': '792ecc1c-beff-4e1a-a6b5-73449b405d36'}
********************************************************************************
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 983, in __getattr__
    return pydantic_extra[item]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'usage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 122, in new_fn
    await fn(**fn_kwargs) if asyncio.iscoroutinefunction(fn) else fn(**fn_kwargs)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 219, in async_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 520, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 217, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/utils.py", line 167, in wrapper
    result, generator_name = await func(*args, **kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/generation/followup_sql_generation_reasoning.py", line 94, in generate_sql_reasoning
    return await generator(
           ^^^^^^^^^^^^^^^^
  File "/src/providers/llm/litellm.py", line 107, in _run
    completions = [connect_chunks(chunk, chunks)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/providers/llm/__init__.py", line 71, in connect_chunks
    "usage": chunk.usage,
             ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 985, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ModelResponseStream' object has no attribute 'usage'
-------------------------------------------------------------------
Oh no an error! Need help with Hamilton?
Join our slack and ask for help! https://join.slack.com/t/hamilton-opensource/shared_invite/zt-2niepkra8-DGKGf_tTYhXuJWBTXtIs4g
-------------------------------------------------------------------

E0605 06:24:47.072 10 wren-ai-service:652] ask pipeline - OTHERS: 'ModelResponseStream' object has no attribute 'usage'
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 983, in __getattr__
    return pydantic_extra[item]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'usage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/web/v1/services/ask.py", line 464, in ask
    await self._pipelines["followup_sql_generation_reasoning"].run(
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 219, in async_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 520, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 217, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/generation/followup_sql_generation_reasoning.py", line 177, in run
    return await self._pipe.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 375, in execute
    raise e
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 366, in execute
    outputs = await self.raw_execute(_final_vars, overrides, display_graph, inputs=inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 326, in raw_execute
    raise e
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 321, in raw_execute
    results = await await_dict_of_tasks(task_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 23, in await_dict_of_tasks
    coroutines_gathered = await asyncio.gather(*coroutines)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 36, in process_value
    return await val
           ^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 91, in new_fn
    fn_kwargs = await await_dict_of_tasks(task_dict)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 23, in await_dict_of_tasks
    coroutines_gathered = await asyncio.gather(*coroutines)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 36, in process_value
    return await val
           ^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 122, in new_fn
    await fn(**fn_kwargs) if asyncio.iscoroutinefunction(fn) else fn(**fn_kwargs)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 219, in async_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 520, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 217, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/utils.py", line 167, in wrapper
    result, generator_name = await func(*args, **kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/generation/followup_sql_generation_reasoning.py", line 94, in generate_sql_reasoning
    return await generator(
           ^^^^^^^^^^^^^^^^
  File "/src/providers/llm/litellm.py", line 107, in _run
    completions = [connect_chunks(chunk, chunks)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/providers/llm/__init__.py", line 71, in connect_chunks
    "usage": chunk.usage,
             ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 985, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ModelResponseStream' object has no attribute 'usage'
```
